### ISSUE TITLE
Reference links suppress emphasis styling on same line

### ISSUE THREAD

**Issue by OccasionalEnthusiast** [yogthos/markdown-clj#102]
The first two are fine...
```clojure
(markdown.core/md-to-html-string
  "abc **xyz** abc"
  :reference-links? true)
;=> "<p>abc <strong>xyz</strong> abc</p>"

(markdown.core/md-to-html-string
  "abc [here][1] abc
  [1]:	http://clojure.org"
  :reference-links? true)
;=> "<p>abc <a href='http://clojure.org'>here</a> abc</p>"
```
But...

```clojure
(markdown.core/md-to-html-string
  "abc **xyz** is [here][1] abc
  [1]:	http://clojure.org"
  :reference-links? true)
;=> "<p>abc **xyz** is <a href='http://clojure.org'>here</a> abc</p>"
```
However...

```clojure
(markdown.core/md-to-html-string
  "abc **xyz**
  is [here][1] abc
  [1]:	http://clojure.org"
  :reference-links? true)
;=> "<p>abc <strong>xyz</strong>   is <a href='http://clojure.org'>here</a> abc</p>"
```
Using version 0.9.89.

Thanks, Kim Wishart (OccasionalEnthusiast)

**Comment by yogthos** [comment]
Ah, so link content needs to be preserved so it's not escaped. Looks like the logic is a bit to aggressive where it also prevents escaping of other content on the line.

**Comment by OccasionalEnthusiast** [comment]
Hi,

Please close/delete this (#102) 'bug'. I discovered I was using a previous version (0.9.8**6**) not the current version 0.9.8**9** as reported.

The current version works correctly. Sorry for wasting your time :(

Kim Wishart (OccasionalEnthusiast)

**Comment by yogthos** [comment]
No worries
