### ISSUE TITLE
image parsing doesn't work if image is on the same line as other text

### ISSUE THREAD

**Issue by simon-brooke** [yogthos/markdown-clj#107]
Interesting wee bugette here:

The following works:

    ![One wiki to rule them all](http://www.weft.scot/images/smeagol.png)

    This is the header. There isn't yet much in it. You could [edit](edit?page=_header) it to provide internal navigation or branding.

The following breaks, rendering the whole line as just characters:

    ![One wiki to rule them all](http://www.weft.scot/images/smeagol.png)This is the header. There isn't yet much in it. You could [edit](edit?page=_header) it to provide internal navigation or branding.

The key to whether it works or not is whether or not there's any further text on the line following the right parenthesis; if there is, it breaks. The [Markdown syntax specification](https://daringfireball.net/projects/markdown/syntax#img) does not specify that there may be no further text on the line.

**Comment by yogthos** [comment]
Can you try adding a space between `)` and `This` in the example?

**Comment by simon-brooke** [comment]
Hi, thanks for the fast reply.

Adding a space does not fix the problem.

I've done a lein ancient today so should be on current version, my project.clj has 

    [markdown-clj "0.9.89" :exclusions [com.keminglabs/cljx]]

If it helps, the project is [here](https://github.com/simon-brooke/smeagol) - I found the bug in the 'develop' branch (or rather in a feature branch off the develop branch).

It's not a show-stopper, and I had thought I'd check out your source and see if I could fix it myself, but other things have come up...

**Comment by yogthos** [comment]
That's for the report, I'll take a look at this when I get a chance. Hopefully, it should be a simple fix. :)

**Comment by SevereOverfl0w** [comment]
This bug seems to be more specific than indicated. It took me a little while to figure out:

`![foo](bar.jpg) this *all* works`

`![foo](bar.jpg) this [doesn't](work.jpg)`

Seems to be to do with having images and links on the same line, more than anything else.

**Comment by yogthos** [comment]
It might be [this bit](https://github.com/yogthos/markdown-clj/blob/2ed50eb21e7661ec29bfb4cb9e202afd5e1addbd/src/cljc/markdown/links.cljc#L155) that's being too aggressive.

**Comment by yogthos** [comment]
closed by https://github.com/yogthos/markdown-clj/pull/109

**Comment by simon-brooke** [comment]
Thanks!
