### ISSUE TITLE
First `<hr/>` tag mangled using `escape-html`

### ISSUE THREAD

**Issue by whitecoop** [yogthos/markdown-clj#112]
Using the `escape-html` function from the README, for some reason the first horizontal rule after a list gets mangled in the output:

```clojure
(defn escape-html [text state]
  (let [sanitized-text (clojure.string/escape text
                         {\& "&amp;"
                          \< "&lt;"
                          \> "&gt;"
                          \" "&quot;"
                          \' "&#39;"})]
    [sanitized-text state]))

(md/md->html "* item\n\n***"
  :replacement-transformers (cons escape-html mdtrans/transformer-vector))
;; => "<ul><li>item</li></ul>&lt;hr/&gt;"

(md->html "* item\n\n***\n\n***"
  :replacement-transformers (cons escape-html mdtrans/transformer-vector))
;; => "<ul><li>item</li></ul>&lt;hr/&gt;<hr/>"
```

vs

```clojure
(md/md->html "* item\n\n***")
;; => "<ul><li>item</li></ul><hr/>"
```

At first I thought that it may have to do with `cons`ing `escape-html` to the front of the `transformer-vector`, but I found that the second one isn't mangled.

**Comment by yogthos** [comment]
The parser is stateful, and the order of transformers is state dependent. So, if `escape-html` is called before the list transformer runs, it could end up being in a bad state.

**Comment by whitecoop** [comment]
Is there a way to guarantee that `escape-html` runs before anything else?

**Comment by yogthos** [comment]
You could just preprocess the text before passing it to `md->html`:

 ```clojure
(defn escape-html [text state]
  (clojure.string/escape text
                                       {\& "&amp;"
                                        \< "&lt;"
                                        \> "&gt;"
                                        \" "&quot;"
                                        \' "&#39;"}))

(-> "* item\n\n***" escape-html md->html)
```
I should probably update the example in the readme to something else though, since this doesn't work as a transformer.

**Comment by whitecoop** [comment]
👍  ok, thanks
