### ISSUE TITLE
:heading-anchors generates code incompatible with HTML5

### ISSUE THREAD

**Issue by jwr** [yogthos/markdown-clj#117]
In HTML5 the a element has no name attribute.

Instead of `<h2><a name="x"></a>x</h2>` we should generate `<h2 id="x">x</h2>`.

See also http://stackoverflow.com/questions/484719/html-anchors-with-name-or-id

**Comment by yogthos** [comment]
Agreed, would you be up doing a pr for this?

**Comment by jwr** [comment]
Ok, I did, though I'm not sure it's worth the effort of doing a full PR.

**Comment by yogthos** [comment]
Thanks, just pushed out a new version to Clojars with the fix.
