### ISSUE TITLE
Seperate lines being squashed.

### ISSUE THREAD

**Issue by rjb25** [yogthos/markdown-clj#119]
If I have two sentences in a mardown file like so:
hey how are you?
Good How about you?
It translates to:
hey how are you?Good How about you?
Is this intentional? Why ignore line breaks? And if you are going to ignore them at least put a space between line content.

**Comment by rjb25** [comment]
This may be an error with the implementation (of cryogen) not passing line breaks to markdown-clj

**Comment by yogthos** [comment]
That is how the [reference implementation](http://daringfireball.net/projects/markdown/dingus) handles this. When a new line is added there is a space inserted between the concatenated content as seen in the [tests here](https://github.com/yogthos/markdown-clj/blob/3f5d5eadde29c2f8d7bcd51b77e69b1330bd0721/test/markdown/md_test.cljc#L69).

**Comment by yogthos** [comment]
Also, I wasn't able to replicate the issue with Cryogen. When I have text on separate lines, it's joined with a space.

**Comment by rjb25** [comment]
Maybe I need to update.

**Comment by rjb25** [comment]
It appears the issue only starts after a code block with an empty line before it. like:
hey

```
hello
```
no
space
***TURNS INTO***
hey
`hello`
nospace

**Comment by rjb25** [comment]
Another issue is that this:
hey
\`\`\`
hello
\`\`\`

**TURNS INTO***

hey
```
hello

```

**Comment by yogthos** [comment]
You're right, the code blocks should work without space around them. The current workaround would be to put space before and after the code blocks for consistent behavior.

**Comment by yogthos** [comment]
I'll take a look at this when I get a chance, but if you'd like to take a look in the meantime feel free to make a pr. :)

**Comment by rjb25** [comment]
Is flexmark going to deprecate markdown-clj? I do not want to go to the trouble if it will.

**Comment by yogthos** [comment]
It's not going to deprecate it as they both have their pros and cons. However, if flexmark works better for you, then I would recommend switching to it.

**Comment by rjb25** [comment]
Ok, I will give a crack at fixing this bug then.

**Comment by yogthos** [comment]
fixed by https://github.com/yogthos/markdown-clj/commit/435fc0a08c36bfacffa4ff62b4fe6ee86d876feb
