### ISSUE TITLE
Bumping out code from code block

### ISSUE THREAD

**Issue by rjb25** [yogthos/markdown-clj#120]
\`\`\`
hey\`\`\`
***=***

\<pre>\<code>\</code>\</pre>hey
Is this desired? If not I can send a pull request.
I would change it to:
\<pre>\<code>hey\</code>\</pre>

**Comment by yogthos** [comment]
This is actually related to the other issue. The way the parser is implemented is that each line is passed through a series of transformers. So, what can happen is that an earlier transformer can modify the state before it gets to the code block transformer.

This can result in the next line being appended to the \`\`\` line when it's parsed. The way that's handled might need to be rethought to support these cases. Currently you could end up with ambiguous lines. For example, you could have something like:

foo\`\`\`
bar

that would end up as "foo\`\`\`bar", and it wouldn't be possible to distinguish from a single line with that content. It would be incorrect to infer end of the code block with the latter.

**Comment by rjb25** [comment]
I think we might be miss understanding each other here. It really seems like the code that was responsible for this error was a simple mistake from copying and changing but forgetting to change string order.

**Comment by yogthos** [comment]
fixed by https://github.com/yogthos/markdown-clj/commit/435fc0a08c36bfacffa4ff62b4fe6ee86d876feb
