### ISSUE TITLE
How to escape a nested code block?

### ISSUE THREAD

**Issue by madstap** [yogthos/markdown-clj#124]
I'm trying to write a markdown example that contains a code block, so I need to escape the three backticks. In github flavored markdown there seems to be 3 ways to do this, but none of them work with markdown-clj.

Examples: (See the raw text of this post in this [gist](https://gist.github.com/madstap/4aba666ec7e1c32c0c3e3316c3f1aec8))

Use 4 spaced indent

    # Things!

    ```klipse-cljs
    (def x 10)
    x
    ```

Use 3 tildes

~~~
# Things!

```klipse-cljs
(def x 10)
x
```
~~~

Use 4 backticks

````
# Things!

```klipse-cljs
(def x 10)
x
```
````

**Comment by yogthos** [comment]
You can escape using the `\` character, e.g:

\`\`\`
(def x 10)
\`\`\`

**Comment by yogthos** [comment]
However, there isn't a way to escape that inside a code block, perhaps it would make sense to make the parser less aggressive about checking for code block start. Currently the \`\`\` line is trimmed, but perhaps it shouldn't be.

**Comment by yogthos** [comment]
using \~\~\~ as an alternative codeblock delimiter would work as well

**Comment by yogthos** [comment]
just pushed out version `0.9.94` that supports \`\`\` inside code indented with 4 spaces

**Comment by yogthos** [comment]
looks like cryogen got updates, so I'll close this one
