### ISSUE TITLE
Short style links that contain two underscores result in added bold tag 

### ISSUE THREAD

**Issue by ericclack** [yogthos/markdown-clj#125]
Not sure this is a defect, but thought I'd raise it anyway. It's something I've seen a few times.

This works as expected:

    > (md-to-html-string "Some content with a <http://www.google.com/abc> link it in")
    "<p>Some content with a <a href=\"http://www.google.com/abc\">http://www.google.com/abc</a> link it in</p>"

But this link gets broken, you can see the `<b>` tags in the result:

    > (md-to-html-string "Some content with a <http://www.google.com/abc__123__efg> link it in")
    "<p>Some content with a <a href=\"http://www.google.com/abc<b>123</b>efg\">http://www.google.com/abc<b>123</b>efg</a> link it in</p>"

**Comment by yogthos** [comment]
Looks like the tags are getting transformed too eagerly in autolinks.

**Comment by yogthos** [comment]
I think I should have the issue fixed, could you try version `0.9.95` and see if everything works as expected?

**Comment by ericclack** [comment]
That works, many thanks for the quick fix.

**Comment by yogthos** [comment]
👍
