### ISSUE TITLE
Bold Italic

### ISSUE THREAD

**Issue by clartaq** [yogthos/markdown-clj#127]
One way to create bold italic is:

`***bold italic***`

which produces ***bold italic*** on most translators, but just plain text in markdown-clj.

This isn't urgent since there are plenty of work-arounds.

**Comment by yogthos** [comment]
Thanks for the report, should be easy enough to add.

**Comment by yogthos** [comment]
should be working in the latest, implemented with https://github.com/yogthos/markdown-clj/commit/a32747bee1e417639a23a3b712170e539751bca0

**Comment by clartaq** [comment]
Thanks for the quick response!

**Comment by yogthos** [comment]
no problem :)
