### ISSUE TITLE
URL's in img elements should not be interpreted as markdown

### ISSUE THREAD

**Issue by hiteshjasani** [yogthos/markdown-clj#133]
We can embed literal HTML and it works as expected:

```
bug.core=> (mc/md-to-html-string "<img src=\"/123.jpg\">")
"<p><img src=\"/123.jpg\"></p>"
```

Except if we have `_` characters in the URL.  Then it tries to interpret them as markdown and messes up the URL:

```
bug.core=> (mc/md-to-html-string "<img src=\"/_123_.jpg\">")
"<p><img src=\"/<i>123</i>.jpg\"></p>"
```

**Comment by dpsutton** [comment]
@hiteshjasani this is addressed in 1.0.8. If this updated version works for you you should be able to close this issue.
