### ISSUE TITLE
Request for a precision detail: which dialect / spec of markdown do you support?

### ISSUE THREAD

**Issue by piotr-yuxuan** [yogthos/markdown-clj#140]
Thanks a lot for that awesome libre work which compiles both to clj and cljs :-) I've skimmed quickly through the code, the PR, and issues but I haven't found a definitive answer to this question: what is your target markdown dialect?

> In March 2016 RFC 7763 and RFC 7764 were published. RFC 7763 introduced MIME type text/markdown with the original variant. RFC 7764 discusses and registered the variants MultiMarkdown, GitHub Flavored Markdown (GFM), Pandoc, CommonMark, and Markdown Extra among others.
>  — [Wikipedia](https://en.wikipedia.org/wiki/Markdown#Standardization)

I think it could be useful for both users and developer to know what ssould be considered a bug, or a feature :-)

**Comment by yogthos** [comment]
The library grew organically as features got added per user requests, so it doesn't strictly follow any of the specs unfortunately. It follows GFM pretty closely, but there may be some deviations.

**Comment by piotr-yuxuan** [comment]
👍
