### ISSUE TITLE
Aligning table data correctly

### ISSUE THREAD

**Issue by 2food** [yogthos/markdown-clj#144]
I noticed that when parsing a table with colons in header to align data the produced html is not correct.
Using the example from [README.md](https://github.com/yogthos/markdown-clj/blob/master/README.md):
```
| Left-Aligned  | Center Aligned  | Right Aligned |
| :------------ | :-------------: | ------------: |
| col 3 is      | some wordy text |         $1600 |
| col 2 is      | centered        |           $12 |
| zebra stripes | are neat        |            $1 |
```
The output is: 
```
<table>
  <thead>
    <tr> 
      <th align='left'>Left-Aligned</th>
      <th align='center'>Center Aligned</th>
      <th align='right'>Right Aligned</th> 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align='left'>col 3 is</td>
      <td align='center'>some wordy text</td>
      <td align='right'>$1600</td>
    </tr>
    <tr>
      <td align='left'>col 2 is</td>
      <td align='center'>centered</td>
      <td align='right'>$12</td>
    </tr>
    <tr>
      <td align='left'>zebra stripes</td>
      <td align='center'>are neat</td>
      <td align='right'>$1</td>
    </tr>
  </tbody>
</table>
```

And according to [w3schools](https://www.w3schools.com/tags/att_td_align.asp) the `align` attribute on `<td>` is no longer supported:

> The align attribute of <td> is not supported in HTML5. Use CSS instead.

`CSS syntax: <td style="text-align:right">`

And indeed it does not render as correctly aligned when i test on chrome. 

(As a side note: the example in the readme.md doesn't have a space between the `:` and the `|`, which causes it to not parse correctly either. )

**Comment by yogthos** [comment]
Thanks for the heads up, I updated the alignment to be set via style instead of using align and updated the example in the docs. Changes are available in version `1.0.4`.
