### ISSUE TITLE
Handle multiple classes on code blocks

### ISSUE THREAD

**Issue by metasoarous** [yogthos/markdown-clj#147]
As mentioned in mpcarolin/markdown-to-hiccup#3, I'd like to be able to handle markdown files with multiple classes specified for code blocks, like this:

    ```edn vega-lite
    {:data {:values [{:a 1 :b 3} {:a 4 :b 8} {:a 7 :b 5}]}
     :mark "point"
     :encoding {:x {:field "a"} :y {:field "b"}}}
    ```

However, instead of being interpreted as a multiple classes on the code block, it renders as this:

    vega
    {:data {:values [{:a 1 :b 3} {:a 4 :b 8} {:a 7 :b 5}]}
     :mark "point"
     :encoding {:x {:field "a"} :y {:field "b"}}}

As mentioned in the issue above, the reason I'd like to do this is so that I can render these blocks as vega visualizations as part of my [oz](https://github.com/metasoarous/oz) dataviz library.

As per your suggestion in that issue, I tried out commonmark-hiccup, and it appears to do what I want with regard to code block's. However, it has some weird behavior which isn't suitable for my purposes (e.g. paragraphs end up looking like `[:p ("content")]` instead of simply `[:p "content"]`). Aside from all that, I'd generally find it useful outside of oz to be able to handle this markdown pattern using `markdown-clj`.

Thanks for your time!

**Comment by yogthos** [comment]
That sounds reasonable, but I'm not sure I'll have time to look at this in the near future. If you'd be up for doing a PR, I can help guide that. The relevant code is in the [code, and codeblock](https://github.com/yogthos/markdown-clj/blob/38d68c312c345786e3ca8e8e4634a234d4b7f12b/src/cljc/markdown/transformers.cljc#L162) functions.

**Comment by metasoarous** [comment]
@yogthos Thanks for reviewing and merging!
