### ISSUE TITLE
Escaping ^ characters

### ISSUE THREAD

**Issue by rutchkiwi** [yogthos/markdown-clj#160]
Hi!

Is there a way to escape ^ characters?

It works fine if they have a space in front of them, but If I've got some text looking like:
`ingredient1^ingredient2`
(where I don't want ingredient2 to be superscript)
it will make it superscript anyways.

Thank you!

**Comment by yogthos** [comment]
Unfortunately that looks like an omissions in the parser at the moment.

**Comment by rutchkiwi** [comment]
Ok thank you! It's not a huge problem for me, but I'll have a look at making a PR for it in the coming weeks.

**Comment by yogthos** [comment]
Thanks, that would be very welcome. :)
