### ISSUE TITLE
Incorrect evaluation of ```

### ISSUE THREAD

**Issue by vganshin** [yogthos/markdown-clj#166]
Hi. There is a bug with interpreting multiline code block. Version: `1.10.4`

```clj
(markdown.core/md-to-html-string "```yaml
list:
- 1
- 2
```"))
output:
<pre><code class="yaml">list:
<ul><li>1- 2
</code></pre></li></ul>
```

**Comment by yogthos** [comment]
Hi, thanks for the heads up. Should be fixed in `1.10.5`, let me know if it looks good on your end.
