### ISSUE TITLE
Calling with :heading-anchors from js?

### ISSUE THREAD

**Issue by rutchkiwi** [yogthos/markdown-clj#197]
Hi, Thanks a lot for this great library.

Apologies as this is a bit of a n00b question.

I want to add get some heading-anchors on my markdown, and it works as expected from clojure. **But how do I do this from JS?** `markdown.core.mdToHtml('#hello \n there', "headingAnchors", true);` does not work.

**Comment by yogthos** [comment]
Hmm not sure why there would be different when compiling to Js. If you're generating on the frontend, maybe there's some security feature in the browser that's sanitizing the reference link that's generated?

**Comment by rutchkiwi** [comment]
hmm i'm not sure what you mean, I simply call this from the console after loading in the library with a script tag. It works, but it doesnt include the ids for fragment links. 
I guess my issue is I don't know how you call clojurescript with keyword args from js - keyword arguments arent a native thing in js. (which isn't really specific to this library, I was just hoping you'd know :)

**Comment by yogthos** [comment]
Oh I see, I misunderstood originally and thought you were just compiling cljs as opposed to calling in from Js. Looking at the code, I think there might need to be explicit keywordization for the params for Js that's not being done currently [here](https://github.com/yogthos/markdown-clj/blob/9d50d0012d20e60578cae20f4474059e8f36b89e/src/cljs/markdown/core.cljs#L47).

```clojure
(when params (apply (partial assoc {}) params))
```
should probably be changed to

```clojure
(some->> params
                 (partition 2) 
                 (reduce (fn [m [k v]] (assoc m (keyword k) v)) {}))
```
then you'd be able to pass in js strings and objects via `mdToHtml`.
