### ISSUE TITLE
Line-spanning links not recognized

### ISSUE THREAD

**Issue by eagleflo** [yogthos/markdown-clj#21]
Hey,

while I was rendering some of my old blog posts with markdown-clj I noticed that line-spanning links such as...

```
[really long
link to github](https://www.github.com/)
```

... don't get parsed correctly. The [reference parser](http://daringfireball.net/projects/markdown/dingus) seems to handle them correctly.

I created a failing test case for this scenario: eagleflo/markdown-clj@05a5fdea.

**Comment by mschaef** [comment]
@yogthos Does this issue also apply to bold, etc.? Looks like it does, but wanted to confirm.

**Comment by yogthos** [comment]
Yeah, the parser reads input line by line, so any tags that are split between lines won't be recognized.
