### ISSUE TITLE
Add support for table syntax

### ISSUE THREAD

**Issue by dannypurcell** [yogthos/markdown-clj#26]
As a markdown-clj user trying to render a github README.md I would like support for the following table syntax:

```
| URL Pattern | Description |
| -------------- | :---------------: |
| `/` | Displays the landing page with content rendered via a handy markdown generator written in Clojure |

| URL Pattern | Description |
| -------------- | ---------------: |
| `/` | Displays the landing page with content rendered via a handy markdown generator written in Clojure |

| URL Pattern | Description |
| -------------- | :--------------- |
| `/` | Displays the landing page with content rendered via a handy markdown generator written in Clojure |

```

So that I can easily render tables such as:

| URL Pattern | Description |
| -------------- | :---------------: |
| `/` | Displays the landing page with content rendered via a handy markdown generator written in Clojure |

| URL Pattern | Description |
| -------------- | ---------------: |
| `/` | Displays the landing page with content rendered via a handy markdown generator written in Clojure |

| URL Pattern | Description |
| -------------- | :--------------- |
| `/` | Displays the landing page with content rendered via a handy markdown generator written in Clojure |

Thanks for all your great work so far!

**Comment by mattbanister** [comment]
I'd like to take a crack at this one too.

**Comment by yogthos** [comment]
sounds like a plan ;)

**Comment by yogthos** [comment]
closed by https://github.com/yogthos/markdown-clj/pull/72
