### ISSUE TITLE
Markdown metadata support

### ISSUE THREAD

**Issue by brunokim** [yogthos/markdown-clj#46]
Some Markdown parsers support storing a metadata header on the file itself. For example,

    Title: Markdown metadata support
    Language: en-US
    Comment: This is an example
        of supported metadata in a markdown file
        and how line breaks are supported
    
    This is the first paragraph.

I'm interested in implementing this feature for markdown-clj, but I'm not yet sure how the interface would look like. We can't add metadata to a String, which would be the ideal solution. One idea is to pass a `parse-meta?` param to `md-to-html` that would then make it return a map.

    (md-to-html-string "Title: title\nAuthor: brunokim\n\nFirst paragraph." :parse-meta? false)
    ;=> "<p>Title: title Author: brunokim</p><p>First paragraph.</p>"
    (md-to-html-string "Title: title\nAuthor: brunokim\n\nFirst paragraph." :parse-meta? true)
    ;=> {:html "<p>First paragraph.</p>" :metadata {:title "title" :author "brunokim"}}

Other concerns are:
* How would we return multiline values? [Python Markdown](https://pythonhosted.org/Markdown/extensions/meta_data.html#accessing-the-meta-data) returns a list for each entry, for example, but we could be a bit more opinionated on this.
* How to implement it? My idea is simply to preprocess as `parse-references` does but consuming the header without resetting the reader.

**Comment by yogthos** [comment]
I like the idea of using the `:parse-meta?` flag to optionally read metadata. Once nice option would be to simply provide metadata as a Clojure map at the start of the file and read it in using the regular reader.

This is how [Cryogen](http://cryogenweb.org/) handles [metadata for posts](https://github.com/cryogen-project/cryogen/blob/master/src/leiningen/new/cryogen/md/posts/2014-12-11-docs.md) and the implementation can be seen [here](https://github.com/cryogen-project/cryogen-core/blob/9de65df523175eed621c8e8c312ad986df19e7f1/src/cryogen_core/compiler.clj#L69).

**Comment by brunokim** [comment]
This syntax is supported in a variety of flavors, such as Python Markdown, Pandoc and MultiMarkdown. Using a Clojure/EDN map seems too specific, and less human-readable. It would be way easier to implement, though.

**Comment by yogthos** [comment]
I'm fairly neutral in regards to the syntax, if the original syntax is already widely used then it would make sense to stick with it though.

**Comment by podviaznikov** [comment]
+1 for this to be implemented.

**Comment by yogthos** [comment]
I won't have time to look at this in the near future, but I would gladly take a pr for the feature if anybody gets to it before I do. :)

**Comment by dankreek** [comment]
I've written some code that enables this feature and it's up at PR #71

**Comment by ITSecMedia** [comment]
👍🏻👍🏻👍🏻
