### ISSUE TITLE
md-to-html escaping valid characters

### ISSUE THREAD

**Issue by rdmcelrath** [yogthos/markdown-clj#50]
While I might be mistaken - this does not appear to be correct to me.

=> (def foo "[Rubber Baby Buggy Bumpers](http://www.somehost.somewhere.net/some_article?foo=synd_bar)")
=> (md/md-to-html-string foo)
"<p><a href='http://www.somehost.somewhere.net/some&#95;article?foo=synd&#95;bar'>Rubber Baby Buggy Bumpers</a></p>"

I believe that the '_' char in the url params - are indeed valid characters for query parameters, and should not be escaped.

Thoughts?

Thanks,
Rod

**Comment by rdmcelrath** [comment]
Rats - ok - lets try that again.

```
=> (def foo "[Rubber Baby Buggy Bumpers](http://www.somehost.somewhere.net/some_article?foo=synd_bar)")
=> (md/md-to-html-string foo)
"<p><a href='http://www.somehost.somewhere.net/some&#95;article?foo=synd&#95;bar'>Rubber Baby Buggy Bumpers</a></p>"
```

Does this render well?

**Comment by rdmcelrath** [comment]
The markdown dingus -
http://daringfireball.net/projects/markdown/dingus

Differs in what this should encode to.  Understand of course you are possibly trying to handle '_' in other parts of the url where it might not be allowed.  I will look at the code a bit.  Would love to offer you a pull request - but I am a total clojure noob.

**Comment by yogthos** [comment]
The current behavior is a bit of a hack, since I convert and special characters to their encoded form so that they're not interpreted by further transformers in the parser. I suppose the simplest thing to do would be to post-process the result to convert any encoded `_` characters back to their original form.

**Comment by yogthos** [comment]
Also, with the current version, you can add a custom transformer for this as follows:

```clojure
(def foo "[Rubber Baby Buggy Bumpers](http://www.somehost.somewhere.net/some_article?foo=synd_bar)")

(defn fix-underscores [text state]
  [(.replaceAll text "&#95;" "_") state])

(md-to-html-string foo :custom-transformers [fix-underscores])
```

**Comment by caryfitzhugh** [comment]
https://github.com/yogthos/markdown-clj/pull/62
