### ISSUE TITLE
bold and link interaction in CLJS?

### ISSUE THREAD

**Issue by caryfitzhugh** [yogthos/markdown-clj#51]
Hello!

I've got a question about how things like bold and links are supposed to interact. Specifically in the CLJS version.

I would expect this to bold the link
```markdown
**[Elizabeth Olsen](http://www.vogue.com/tag/celebrity/elizabeth-olsen)** 
```
**[Elizabeth Olsen](http://www.vogue.com/tag/celebrity/elizabeth-olsen)** 

I believe this should bold the link as well:
```markdown
[**Elizabeth Olsen**](http://www.vogue.com/tag/celebrity/elizabeth-olsen)
```

[**Elizabeth Olsen**](http://www.vogue.com/tag/celebrity/elizabeth-olsen)

However, when I do the second one above in cljs, it does not seem to bold the link. It simply passes along the *s in the link name.

Sadness:
![16v9e21](https://cloud.githubusercontent.com/assets/445848/7392429/c0f6c3a0-ee55-11e4-80b6-49ed83c2a24a.jpg)

From this:
![udipa56](https://cloud.githubusercontent.com/assets/445848/7392442/d16255ba-ee55-11e4-8cdc-1e88426639fe.jpg)

Any thoughts?  I notice that github parses it as I would expect, so do a few other places online.

I'll poke about in the code, maybe see if I can help fix it...

**Comment by caryfitzhugh** [comment]
I put some code in the PR to fix this.
If we can get it pulled in and redeployed to clojars that would be sweet!

**Comment by yogthos** [comment]
just pushed out `[markdown-clj "0.9.66"]` with the fix, thanks for doing the investigation and pr for this :)

**Comment by caryfitzhugh** [comment]
Thanks!
