### ISSUE TITLE
reference style links

### ISSUE THREAD

**Issue by martinklepsch** [yogthos/markdown-clj#55]
Not sure how easy this would be to implement but I'd like to see `markdown-clj` support reference style links. Example as documented on [daringfireball.net](http://daringfireball.net/projects/markdown/syntax#link):

```markdown
This is [an example][id] reference-style link.
This is [an example] [id] reference-style link with a space between brackets.
[id]: http://example.com/  "Optional Title Here"
```

Thoughts?

**Comment by yogthos** [comment]
I think [this](https://github.com/yogthos/markdown-clj#reference-style-links) might be what you're looking for. The ref style links are disabled by default as they require as second pass.

**Comment by martinklepsch** [comment]
@yogthos of course. Should've checked the README more thoroughly, thanks.
