### ISSUE TITLE
Add support for footnotes

### ISSUE THREAD

**Issue by rcarmo** [yogthos/markdown-clj#59]
Hi there!

It would be great if this supported footnotes, as per the MultiMarkdown extensions.

**Comment by yogthos** [comment]
I think it would be a nice feature, but I wouldn't have time to look at it at the moment. Would you be open to doing a pr for it?

**Comment by mattbanister** [comment]
Hi @yogthos @rcarmo 

I'll see if I can put together a PR for this.

**Comment by yogthos** [comment]
:+1:

**Comment by mattbanister** [comment]
Hi @yogthos 

Thanks!  You can close this issue as well.

Matt

**Comment by yogthos** [comment]
:+1:
