### ISSUE TITLE
Bug: Last line not shown if there's a single paragraph after a list

### ISSUE THREAD

**Issue by ricardojmendez** [yogthos/markdown-clj#61]
If you convert:

    - l1
    - l2
    - l3
    
    paragraph

The `paragraph` will not be rendered unless there's at least an empty line following it (needs to have a carriage return after it, or another paragraph).

![screen shot 2015-08-21 at 12 27 06 pm](https://cloud.githubusercontent.com/assets/31263/9405389/fa57cbf4-47ff-11e5-9973-5bd1387759f2.png)

If there _is_ a line after, it's all rendered properly, even if that second line does not have a carriage return.

![screen shot 2015-08-21 at 12 30 11 pm](https://cloud.githubusercontent.com/assets/31263/9405451/73f43420-4800-11e5-83b5-fa8a8537d57c.png)

**Comment by yogthos** [comment]
I believe it's just a quirk with the demo where I reprocess the text using the `onkeyup` event.

**Comment by ricardojmendez** [comment]
I noticed on a project where I use the library, and decided to test on the demo as well to make sure it wasn't one of my replacement transformers breaking things.

If it was an `onkeyup` issue, I expect you:
- Wouldn't get the "second" appear on the second test,
- Wouldn't get the last item on a list to appear until you've pressed enter, whereas they're updated on the fly.

I've only seen this happen when there's a single paragraph following a list.

**Comment by yogthos** [comment]
Hmm, but the library will render the correct output with the:

```clojure
(md-to-html-string "- l1\n- l2\n- l3\n\n\nparagraph")
=>"<ul><li>l1</li><li>l2</li><li>l3</li></ul><p>paragraph</p>"
```

and on Cljs side I get the correct result with this as well:

```clojure
(set!
  (.-innerHTML (.-body js/document))
  (md->html "\n- l1\n- l2\n- l3\n\n\nparagraph"))
```

**Comment by ricardojmendez** [comment]
On your example, you have three `\n` between l3 and the paragraph. Perhaps there's something I'm missing - is this a Markdown requirement?  If you test it on the demo, you'll see that if there's more than one line in between them, `paragraph` is rendered as expected, if there's only one blank line (two `\n`) it's not.

Let me cook up a cljs test on my end.

**Comment by ricardojmendez** [comment]
Testing from figwheel with no replacement transformers:

```
cljs.user=> (md->html "- l1\n- l2\n- l3\n\nparagraph")
"<ul><li>l1</li><li>l2</li><li>l3</li></ul>"

cljs.user=> (md->html "- l1\n- l2\n- l3\n\nparagraph\n")
"<ul><li>l1</li><li>l2</li><li>l3</li></ul><p>paragraph</p>"
```

**Comment by yogthos** [comment]
Oh I think the issue is that you need 3 new lines after the list. This is a quirk with handling lists that can have blank lines between items.

**Comment by ricardojmendez** [comment]
Is this working as expected then? Shouldn't it consider the list to have ended at the first time a new line does not start with a list item, like it considers it done if the paragraph does have a new line at the end?

**Comment by yogthos** [comment]
It does look like a bug, it looks like the check happens when the next line is processed and if the paragraph is the end of input then it doesn't get handled correctly.

**Comment by ricardojmendez** [comment]
True, md->html and md-to-html-string are not behaving consistently here.

```
=> (md-to-html-string "- l1\n- l2\n- l3\n\nparagraph")
"<ul><li>l1</li><li>l2</li><li>l3</li></ul><p>paragraph</p>"
```

**Comment by yogthos** [comment]
I'll take a look, it shouldn't be hard to fix :)

**Comment by yogthos** [comment]
OK pushed out `0.9.69` to Clojars with a fix, I just ended up appending a `\n` at the end of the input string in Cljs to handle the edge case.

**Comment by ricardojmendez** [comment]
Odd. Just updated, cleaned, and I still get the same result on ClojureScript. Let me check.

**Comment by yogthos** [comment]
I did try it locally and seemed ok. :)

**Comment by ricardojmendez** [comment]
Browser cache issue after the update. Should have cleaned it as well. Cheers!
