### ISSUE TITLE
Fenced code blocks have \n at the end

### ISSUE THREAD

**Issue by dvcrn** [yogthos/markdown-clj#75]
Hi, noticed another thing:

```
just a test
```

turns into
![screen shot 2015-11-11 at 2 28 37 pm](https://cloud.githubusercontent.com/assets/688326/11084582/86951cb4-8880-11e5-8724-169cbeafc785.png)

which looks like this:
![screen shot 2015-11-11 at 2 29 44 pm](https://cloud.githubusercontent.com/assets/688326/11084593/b1c89e10-8880-11e5-9d52-b6629bffb885.png)

**Comment by yogthos** [comment]
this appears to render as expected though

**Comment by dvcrn** [comment]
Not quite. The block has a line too much which makes the entire constract bigger than it should be:

```
just a test
```
vs
```
just a test

```

**Comment by yogthos** [comment]
ah ok, I tried in the [demo page](https://cdn.rawgit.com/yogthos/markdown-clj/master/demo/markdown.html) and it looked the same, but could just be the styling

**Comment by yogthos** [comment]
would just be a matter of updating [here](https://github.com/yogthos/markdown-clj/blob/53f70c9550d44bbf8b1ef6bf9964a8b5ae1fafe1/src/cljc/markdown/transformers.cljc#L256)

**Comment by yogthos** [comment]
just pushed out `0.9.80` that should fix this, let me know if it works for you
