### ISSUE TITLE
Support for (non-standard) optional href 'target' attribute

### ISSUE THREAD

**Issue by juskrey** [yogthos/markdown-clj#76]
That is, for being able to generate
```html
<a href="http://example.com" target="_blank">example</a>
```
Without having to use raw html markdown insertions.

Is this possible? Motivation is quite clear, since the described case is the default modus operandi for majority of web template markdown usage.

**Comment by yogthos** [comment]
Currently, there's no built in support as it's not part of the markdown spec. However, you could add a [custom transformer](https://github.com/yogthos/markdown-clj#customizing-the-parser) that could parse such tags.

**Comment by juskrey** [comment]
Thanks for explanation!
