### ISSUE TITLE
Thoughts on en-dash and em-dash?

### ISSUE THREAD

**Issue by jonpither** [yogthos/markdown-clj#78]
I.e. some markdown converters convert -- to en-dash and --- to em-dash. Would a PR be welcome?

**Comment by yogthos** [comment]
Absolutely, but It would probably make sense to make it an optional behavior, since it would affect existing users otherwise.

**Comment by yogthos** [comment]
actually, since there's no tests for that yet, I think I'll just add it in as the default :)

**Comment by yogthos** [comment]
closed by https://github.com/yogthos/markdown-clj/pull/79
