### ISSUE TITLE
No such namespace error 0.9.82

### ISSUE THREAD

**Issue by pbaille** [yogthos/markdown-clj#81]
No such namespace error when trying to use version 0.9.82 from clojurescript
Works well with 0.9.81

**Comment by yogthos** [comment]
What is the namespace that's missing with `0.9.82`. I'm not able to reproduce this locally, the common issues can be an old version of ClojureScript in the project or lein-cljsbuild.

**Comment by pbaille** [comment]
ok, thank you, I will check that
