### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by SevereOverfl0w** [yogthos/markdown-clj#85]
You have the .travis.yml file in the repo, but don't seem to have enabled travis on your [dashboard](https://travis-ci.org/profile/yogthos)

**Comment by yogthos** [comment]
I think I had problems with cljx compilation and travis before, but now that I'm using cljc it's probably time to re-enable ;)

**Comment by SevereOverfl0w** [comment]
I'll send over my next super simple PR once it's on, and test it out for you :smile:

**Comment by yogthos** [comment]
no worries, just added back in :)
