### ISSUE TITLE
Reference links interfere with other formatting on the same line.

### ISSUE THREAD

**Issue by Idorobots** [yogthos/markdown-clj#89]
``` clojure
(md-to-html-string "*em* [ref][test]\n\n[test]: # 'title'" :reference-links? true)
```

Results in:

``` html
<p>*em* <a href='#' title='title'>ref</a></p>
```

It appears the problem is [here](https://github.com/yogthos/markdown-clj/blob/master/src/cljc/markdown/links.cljc#L107-L110). After replacing all refs, it'll freeze the line so no other transformers can change it.

**Comment by yogthos** [comment]
Yeah, looks like freezing would need to be a bit more selective.

**Comment by yogthos** [comment]
@Idorobots I just push a new version that should fix the issue, let mew know if everything works as epxected

**Comment by yogthos** [comment]
fixed by https://github.com/yogthos/markdown-clj/commit/66f289c07c08045a44f6b261db5ecaab955e3a0d

**Comment by Idorobots** [comment]
LGTM, thanks!
