### ISSUE TITLE
Non-leading hashes in headings are ignored

### ISSUE THREAD

**Issue by bjeanes** [yogthos/markdown-clj#93]
E.g.

```md
# Ticket #123

Foo
```

In other renderers, including GitHub's, the `#123` would be present in the heading, as demonstrated inline here:

> # Ticket #123
>
> Foo

In `markdown-clj` (at least in the cljs demo), the `#123` is truncated and only `Ticket` appears in the header:

![screen shot 2016-02-29 at 11 59 52](https://cloud.githubusercontent.com/assets/2560/13383322/fd70228c-dedb-11e5-8a65-1f09ee593c63.png)

**Comment by yogthos** [comment]
Yeah, I'd say this is a bug in the parser, should be a simple fix though. I might not have time to look at it in the near future, but if you're up for doing a pr before I get to it, I'd be glad to help and release a new version.

**Comment by bjeanes** [comment]
If I start using this, I will. I was just playing with it in the demo and noticed the bug.

**Comment by yogthos** [comment]
sounds good and thanks for the heads up

**Comment by yogthos** [comment]
By the way just tested the latest version, it looks like it's working fine. I think I just forgot to update the demo site.

**Comment by yogthos** [comment]
updated the demo site with the latest

**Comment by bjeanes** [comment]
Oh nice. Great news :)
