### ISSUE TITLE
When the header is immediately followed by text, the next space is gobbled

### ISSUE THREAD

**Issue by vermiculus** [yogthos/markdown-clj#98]
```clojure
(= (markdown/md-to-html-string "#\n1\n2")    ;"<h1></h1>12"
   (markdown/md-to-html-string "#\n\n1\n2")) ;"<h1></h1><p>1 2</p>"
```

When a heading immediately precedes text, a space isn't added to the second line of text when it joins with the third.

That is,
```markdown
#
1
2
```
yields
```html
<h1></h1>12
```
instead of
```html
<h1></h1><p>1 2</p>
```

**Comment by yogthos** [comment]
Just pushed out a fix with the version `0.9.89`, let me know if everything looks good.

**Comment by vermiculus** [comment]
Fix works; just a reminder to update the demo page 😄

Thanks!

**Comment by yogthos** [comment]
perfect, just updated
