### ISSUE TITLE
Support conversion to other targets than HTML ?

### ISSUE THREAD

**Issue by dgellow** [yogthos/markdown-clj#99]
Hello,

I have a project where I have a source file in markdown and I want to produce multiple exports in different formats.
At the moment markdown-clj only supports HTML but I'm thinking that maybe we could have something like an `Exporter` protocol and a generic `(markdown.core/render "#foo" my-exporter)` or something else in the same idea.

Do you think it's something in the scope of this project or I'm better to find another one or create a fork?
Btw I would be happy to help implement that kind of feature.

**Comment by yogthos** [comment]
The parser doesn't use an intermediary format, and it just writes HTML to the output directly. So, modifying it to create an internal data structure that the output is then generated from would be quite a bit of work I suspect. It would probably be easier to wrap something like [pegdown](https://github.com/sirthias/pegdown) instead.

**Comment by dgellow** [comment]
Just to share some things I found:

[markdown2clj](https://github.com/nilenso/markdown2clj), a wrapper around commonmark-java. That's exactly what I was looking for, it gives me an AST I can use to generate any format I want.
I created [mdmorph](https://github.com/dgellow/mdmorph), a (incomplete and dirty) lib to transform a markdown2clj AST in something else.

**Comment by yogthos** [comment]
Yeah, markdown2clj looks like it fits the bill perfectly, glad to hear you got things working. 👍
